import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// 40 categories × 50 products each = 2000 products
const CATEGORIES: Record<string, string[]> = {
  upcoming: [
    "AI Smart School ERP Cloud","AI Hospital ERP Pro","AI Real Estate CRM","AI Inventory Ultra","AI Retail POS Cloud",
    "AI Restaurant Automation","AI Hotel PMS Pro","AI Logistics Tracker","AI Forex Trading Bot","AI Crypto Trading Bot",
    "AI Construction ERP","AI HRMS Global","AI Payroll Advanced","AI Warehouse Smart","AI Agriculture ERP",
    "AI Fleet Management","AI Loan Management","AI Microfinance ERP","AI Pharmacy Manager","AI Clinic Pro",
    "AI Legal Case Manager","AI Court Management","AI Government ERP","AI NGO Management","AI Gym Management",
    "AI Sports Club ERP","AI Salon Spa ERP","AI Fashion POS","AI E-Commerce Multi Vendor","AI Marketplace Builder",
    "AI MLM Software","AI Billing Software","AI Transport School","AI University ERP","AI Coaching Institute ERP",
    "AI Library Automation","AI Exam Management","AI Biometric Attendance","AI Face Recognition Access","AI Security Surveillance",
    "AI Mining ERP","AI Manufacturing ERP","AI Factory IoT System","AI Solar Energy ERP","AI Telecom Billing",
    "AI Cloud Hosting Panel","AI Cybersecurity Suite","AI Data Analytics Studio","AI Investment Portfolio","AI Capital Project ERP",
  ],
  on_demand: [
    "Custom School ERP","Custom Hospital ERP","Custom POS Software","Custom CRM Builder","Custom ERP Builder",
    "Custom Marketplace App","Custom Banking Core","Custom Trading Platform","Custom Taxi App","Custom Food Delivery App",
    "Custom Learning App","Custom OTT Platform","Custom Payment Gateway","Custom Wallet App","Custom Franchise System",
    "Custom NGO ERP","Custom Insurance System","Custom Logistics ERP","Custom HRMS","Custom Payroll",
    "Custom Property Portal","Custom Warehouse","Custom Fleet Tracker","Custom Agriculture ERP","Custom Dairy ERP",
    "Custom Pharma ERP","Custom Laboratory System","Custom Government Portal","Custom Municipality ERP","Custom Legal Tech",
    "Custom Court ERP","Custom Gym App","Custom Salon App","Custom Booking System","Custom Event Manager",
    "Custom Mining ERP","Custom Construction ERP","Custom Manufacturing ERP","Custom Billing App","Custom Subscription SaaS",
    "Custom AI Chatbot","Custom AI Automation","Custom Data Dashboard","Custom Security System","Custom CCTV Software",
    "Custom Biometric System","Custom Investment App","Custom Stock Trading App","Custom Microfinance App","Custom Capital Management",
  ],
  top_selling: [
    "School ERP Bestseller","Hospital ERP Bestseller","Retail POS Bestseller","Restaurant POS Bestseller","Hotel PMS Bestseller",
    "CRM Pro Bestseller","ERP Suite Bestseller","Billing Pro Bestseller","Pharmacy Bestseller","Clinic Manager Bestseller",
    "Inventory Pro Bestseller","Accounting Suite Bestseller","HR Manager Bestseller","Payroll Pro Bestseller","Fleet Manager Bestseller",
    "Logistics Hub Bestseller","Warehouse Pro Bestseller","Real Estate CRM Bestseller","Construction ERP Bestseller","Education LMS Bestseller",
    "Coaching ERP Bestseller","University ERP Bestseller","E-Commerce Suite Bestseller","MLM Platform Bestseller","Gym Manager Bestseller",
    "Salon Manager Bestseller","Food Delivery App Bestseller","Taxi App Bestseller","Hotel Booking Bestseller","Travel Agent ERP Bestseller",
    "Insurance Manager Bestseller","Microfinance Bestseller","Agriculture ERP Bestseller","Dairy Manager Bestseller","Mining ERP Bestseller",
    "Manufacturing ERP Bestseller","Telecom Billing Bestseller","Solar ERP Bestseller","NGO Manager Bestseller","Legal Case Bestseller",
    "Government Portal Bestseller","Municipality ERP Bestseller","Exam System Bestseller","Library System Bestseller","Transport ERP Bestseller",
    "Biometric System Bestseller","CCTV Software Bestseller","Data Analytics Bestseller","Investment Manager Bestseller","Capital ERP Bestseller",
  ],
  evergreen: [
    "School ERP Standard","Hospital ERP Standard","Retail POS Standard","Restaurant Manager Standard","Hotel Manager Standard",
    "CRM Standard","ERP Core Standard","Billing Manager Standard","Pharmacy Standard","Clinic Standard",
    "Inventory Manager Standard","Accounting Standard","HR Manager Standard","Payroll Standard","Fleet Standard",
    "Logistics Standard","Warehouse Standard","Real Estate Standard","Construction Standard","LMS Standard",
    "Coaching Standard","University Standard","E-Commerce Standard","MLM Standard","Gym Standard",
    "Salon Standard","Food App Standard","Taxi Standard","Booking Standard","Travel Standard",
    "Insurance Standard","Finance Standard","Agriculture Standard","Dairy Standard","Mining Standard",
    "Manufacturing Standard","Telecom Standard","Energy Standard","NGO Standard","Legal Standard",
    "Government Standard","Municipality Standard","Exam Standard","Library Standard","Transport Standard",
    "Biometric Standard","Security Standard","Analytics Standard","Investment Standard","Capital Standard",
  ],
  education: [
    "School ERP Pro","College ERP Pro","University ERP Pro","Coaching Institute ERP","Exam Management System",
    "Library Automation System","Transport Management System","Hostel ERP Pro","Online Learning LMS","Student Portal App",
    "Parent Portal App","Teacher Portal App","Biometric Attendance System","Result Automation System","Certificate Generator Pro",
    "Fee Management System","AI Homework Checker","AI Question Generator","Virtual Classroom Pro","Digital Marksheet System",
    "School ERP Cloud","College ERP Cloud","University ERP Cloud","Coaching Cloud ERP","Exam Cloud System",
    "Library Cloud System","Transport Cloud System","Hostel Cloud ERP","LMS Cloud Pro","Student App Cloud",
    "Parent App Cloud","Teacher App Cloud","Biometric Cloud System","Result Cloud System","Certificate Cloud Pro",
    "Fee Cloud System","AI Tutor Pro","AI Assessment Engine","Smart Classroom System","E-Marksheet Cloud",
    "School ERP AI","College ERP AI","University ERP AI","Coaching AI ERP","Exam AI System",
    "Library AI System","Transport AI System","Hostel AI ERP","LMS AI Pro","Education Analytics Pro",
  ],
  healthcare: [
    "Hospital ERP Complete","Clinic Management Pro","Patient Portal System","Lab Management System","Pharmacy Chain Manager",
    "Ambulance Tracking System","Blood Bank Manager","Radiology System Pro","OPD Manager Pro","IPD Manager Pro",
    "Hospital ERP Cloud","Clinic Cloud Manager","Patient Cloud Portal","Lab Cloud System","Pharmacy Cloud Manager",
    "Ambulance Cloud Tracker","Blood Bank Cloud","Radiology Cloud Pro","OPD Cloud Manager","IPD Cloud Manager",
    "Hospital ERP AI","Clinic AI Manager","Patient AI Portal","Lab AI System","Pharmacy AI Manager",
    "Telemedicine Platform","Health Insurance System","Medical Billing Pro","Pathology System Pro","Dental Clinic Manager",
    "Eye Hospital ERP","Ayurvedic Clinic ERP","Veterinary Clinic Manager","Mental Health Platform","Nursing Home ERP",
    "Rehabilitation Center ERP","Hospital Chain Manager","Medical Store POS","Diagnostic Center ERP","Home Healthcare App",
    "ICU Management System","Surgery Scheduler Pro","Medical Records System","Vaccination Tracker","Health Analytics Dashboard",
    "Hospital HR Manager","Medical Equipment Tracker","Clinical Trial Manager","Patient Feedback System","Healthcare CRM Pro",
  ],
  finance: [
    "Banking Core System","Loan Management Pro","Microfinance ERP","Investment Portfolio Manager","Stock Trading Platform",
    "Mutual Fund Manager","Insurance Manager Pro","Tax Filing System","Accounting Suite Pro","Financial Analytics Dashboard",
    "Banking Cloud System","Loan Cloud Manager","Microfinance Cloud ERP","Investment Cloud Manager","Stock Cloud Platform",
    "Mutual Fund Cloud","Insurance Cloud Manager","Tax Cloud System","Accounting Cloud Suite","Finance Cloud Analytics",
    "Banking AI System","Loan AI Manager","Microfinance AI ERP","Investment AI Manager","Stock AI Platform",
    "NBFC Manager Pro","Credit Union ERP","Forex Trading Platform","Crypto Exchange Platform","Digital Wallet System",
    "Payment Gateway Pro","Remittance System","Invoice Factoring System","Asset Management Pro","Wealth Management System",
    "Budget Planner Pro","Expense Manager Pro","Audit Management System","Compliance Manager","Financial CRM Pro",
    "Debt Collection System","EMI Calculator Pro","Credit Score System","Financial Reporting Suite","Treasury Management System",
    "Risk Assessment System","Pension Manager Pro","Cooperative Society ERP","Money Lending Manager","Capital Markets Platform",
  ],
  retail: [
    "Retail POS Complete","Supermarket POS Pro","Grocery Store Manager","Electronics Store POS","Clothing Store POS",
    "Jewelry Store POS","Furniture Store POS","Hardware Store POS","Book Store POS","Mobile Store POS",
    "Retail POS Cloud","Supermarket Cloud POS","Grocery Cloud Manager","Electronics Cloud POS","Clothing Cloud POS",
    "Jewelry Cloud POS","Furniture Cloud POS","Hardware Cloud POS","Book Cloud POS","Mobile Cloud POS",
    "Retail POS AI","Supermarket AI POS","Grocery AI Manager","Electronics AI POS","Clothing AI POS",
    "Multi Store POS","Franchise POS Manager","Wholesale POS Pro","Kirana Store POS","Medical Store POS",
    "Optical Store POS","Pet Store POS","Toy Store POS","Gift Shop POS","Cosmetic Store POS",
    "Bakery Store POS","Sweet Shop POS","Stationery Store POS","Sports Store POS","Auto Parts POS",
    "Tire Shop POS","Paint Store POS","Electrical Store POS","Plumbing Store POS","Garden Store POS",
    "Liquor Store POS","Tobacco Shop POS","Craft Store POS","Fabric Store POS","General Store POS",
  ],
  restaurant: [
    "Restaurant POS Complete","Cafe POS Manager","Fast Food POS Pro","Fine Dining POS","Bar & Pub POS",
    "Food Court POS","Cloud Kitchen Manager","Catering Manager Pro","Bakery POS Complete","Sweet Shop Manager",
    "Restaurant POS Cloud","Cafe Cloud Manager","Fast Food Cloud POS","Fine Dining Cloud","Bar Cloud POS",
    "Food Court Cloud","Cloud Kitchen Cloud","Catering Cloud Manager","Bakery Cloud POS","Sweet Shop Cloud",
    "Restaurant POS AI","Cafe AI Manager","Fast Food AI POS","Fine Dining AI","Bar AI Manager",
    "Multi Restaurant Manager","Franchise Restaurant POS","Food Delivery Manager","Table Reservation System","Kitchen Display System",
    "Menu Management Pro","Recipe Manager Pro","Inventory for Restaurant","Waste Management Restaurant","Staff Scheduler Restaurant",
    "Restaurant CRM Pro","Customer Loyalty Restaurant","Online Ordering System","Restaurant Analytics Pro","Food Safety Manager",
    "Restaurant Chain ERP","Commissary Kitchen Manager","Food Truck POS","Juice Bar POS","Ice Cream Shop POS",
    "Pizza Shop POS","Biryani House POS","Chinese Restaurant POS","Thai Restaurant POS","Indian Restaurant POS",
  ],
  hotel: [
    "Hotel PMS Complete","Resort Manager Pro","Guest House Manager","Lodge Manager Pro","Hostel Booking System",
    "Hotel PMS Cloud","Resort Cloud Manager","Guest House Cloud","Lodge Cloud Manager","Hostel Cloud System",
    "Hotel PMS AI","Resort AI Manager","Guest House AI","Lodge AI Manager","Hostel AI System",
    "Hotel Chain Manager","Boutique Hotel PMS","Service Apartment Manager","Motel Manager Pro","Hotel Booking Engine",
    "Channel Manager Pro","Revenue Manager Pro","Hotel CRM System","Housekeeping Manager","Maintenance Manager Hotel",
    "Hotel F&B Manager","Banquet Manager Pro","Conference Manager","Spa Manager Hotel","Pool Manager Hotel",
    "Hotel Loyalty System","Guest Feedback System","Hotel Analytics Dashboard","Night Audit System","Hotel POS System",
    "Room Service Manager","Laundry Manager Hotel","Mini Bar Manager","Hotel HR System","Hotel Accounting System",
    "Hotel Procurement System","Lost & Found Manager","Hotel Security System","Valet Parking Manager","Hotel Event Manager",
    "Hotel Marketing Suite","OTA Integration Manager","Hotel Rate Manager","Hotel Forecast System","Hotel Budget Manager",
  ],
  logistics: [
    "Logistics ERP Complete","Courier Management Pro","Freight Management System","Supply Chain Manager","Last Mile Delivery System",
    "Logistics Cloud ERP","Courier Cloud Manager","Freight Cloud System","Supply Chain Cloud","Last Mile Cloud",
    "Logistics AI ERP","Courier AI Manager","Freight AI System","Supply Chain AI","Last Mile AI",
    "Fleet Manager Pro","Vehicle Tracking System","Route Optimization System","Dispatch Manager Pro","Load Planning System",
    "Container Tracking System","Cold Chain Manager","Reverse Logistics System","Cross Docking Manager","Yard Management System",
    "Transportation Management","Cargo Management System","Parcel Tracking System","Delivery Route Planner","Driver Management System",
    "Fuel Management System","Tire Management System","Logistics CRM Pro","Logistics Analytics Dashboard","Logistics Billing System",
    "Customs Clearance Manager","Import Export Manager","Port Management System","Air Cargo Manager","Sea Freight Manager",
    "Rail Logistics Manager","Truck Load Manager","LTL Freight Manager","Logistics Marketplace","3PL Manager Pro",
    "4PL Platform System","Logistics Insurance System","Claims Manager Logistics","Logistics HR System","Logistics Budget Manager",
  ],
  real_estate: [
    "Real Estate CRM Complete","Property Portal Pro","Builder ERP System","Real Estate Cloud CRM","Property Cloud Portal",
    "Builder Cloud ERP","Real Estate AI CRM","Property AI Portal","Builder AI ERP","Broker Management System",
    "Rental Management Pro","Lease Management System","Facility Management ERP","Property Maintenance System","Tenant Portal System",
    "Landlord Portal System","Real Estate Marketing Suite","Property Listing Platform","Real Estate Analytics Dashboard","Mortgage Calculator Pro",
    "Home Loan Manager","Property Valuation System","Land Registry System","Plot Management System","Colony Management ERP",
    "Society Management ERP","Apartment Manager Pro","Villa Management System","Commercial Property Manager","Mall Management System",
    "Warehouse Property Manager","Office Space Manager","Coworking Space Manager","PG Hostel Manager","Service Apartment Manager",
    "Real Estate Accounting System","Property Tax Manager","Real Estate Legal Manager","Property Insurance Manager","Real Estate Auction System",
    "Property Investment Manager","REITs Manager Pro","Real Estate Fund Manager","Property CRM Mobile","Virtual Tour Manager",
    "Property Comparison Tool","Real Estate Lead Manager","Open House Manager","Agent Commission Manager","Real Estate Budget Manager",
  ],
  construction: [
    "Construction ERP Complete","Project Management Construction","Site Manager Pro","Construction Cloud ERP","Project Cloud Construction",
    "Site Cloud Manager","Construction AI ERP","Project AI Construction","Site AI Manager","Contractor Management System",
    "Sub Contractor Manager","Material Manager Pro","Equipment Manager Pro","Labor Manager Pro","Safety Manager Construction",
    "Quality Manager Construction","Cost Estimation System","BOQ Manager Pro","Tender Management System","Procurement Construction",
    "Billing Construction Pro","Invoice Construction System","Progress Report System","Daily Report Construction","Inspection Manager Pro",
    "Punch List Manager","RFI Manager Pro","Change Order Manager","Document Manager Construction","Drawing Manager Pro",
    "BIM Manager System","Survey Manager Pro","Soil Testing Manager","Concrete Testing System","Steel Tracking System",
    "Rebar Manager Pro","Formwork Manager","Scaffolding Manager","Crane Management System","Heavy Equipment Manager",
    "Construction HR System","Construction Payroll","Construction Accounting","Construction CRM Pro","Construction Analytics",
    "Construction Insurance Manager","Construction Legal Manager","Construction Safety Audit","Environmental Compliance Manager","Construction Budget Manager",
  ],
  manufacturing: [
    "Manufacturing ERP Complete","Factory Manager Pro","Production Planning System","Manufacturing Cloud ERP","Factory Cloud Manager",
    "Production Cloud System","Manufacturing AI ERP","Factory AI Manager","Production AI System","Bill of Materials Manager",
    "Work Order Manager","Shop Floor Manager","Quality Control System","Inventory Manufacturing","Raw Material Manager",
    "Finished Goods Manager","WIP Tracking System","Machine Management System","Maintenance Manager Factory","OEE Dashboard Pro",
    "MES System Pro","SCADA Integration System","PLC Manager Pro","IoT Factory System","Smart Factory Platform",
    "Batch Processing System","Process Manufacturing ERP","Discrete Manufacturing ERP","Assembly Line Manager","Packaging Manager Pro",
    "Labeling System Pro","Barcode Manager Factory","RFID Factory System","Vendor Manager Manufacturing","Purchase Manager Manufacturing",
    "Sales Manager Manufacturing","Cost Accounting Manufacturing","Job Costing System","Standard Costing System","Activity Based Costing",
    "Manufacturing HR System","Manufacturing Payroll","Manufacturing CRM","Manufacturing Analytics","Manufacturing Compliance",
    "Lean Manufacturing System","Six Sigma Manager","Kaizen Manager Pro","5S Manager System","Manufacturing Budget Manager",
  ],
  agriculture: [
    "Agriculture ERP Complete","Farm Management Pro","Crop Management System","Agriculture Cloud ERP","Farm Cloud Manager",
    "Crop Cloud System","Agriculture AI ERP","Farm AI Manager","Crop AI System","Livestock Management System",
    "Poultry Management System","Dairy Farm Manager","Fishery Management System","Aquaculture Manager","Nursery Management System",
    "Seed Management System","Fertilizer Manager Pro","Pesticide Manager Pro","Irrigation Management System","Weather Monitoring System",
    "Soil Analysis Manager","Harvest Manager Pro","Post Harvest Manager","Cold Storage Manager Agriculture","Supply Chain Agriculture",
    "Market Price Tracker Agriculture","Agricultural Marketplace","Farmer CRM System","Agricultural Finance Manager","Crop Insurance Manager",
    "Government Subsidy Tracker","Agriculture Analytics Dashboard","Precision Farming System","Drone Farming Manager","GPS Mapping Agriculture",
    "Agriculture HR System","Agriculture Payroll","Farm Accounting System","Agriculture Compliance","Agriculture Research Manager",
    "Organic Farming Manager","Hydroponics Manager","Vertical Farming System","Smart Greenhouse Manager","Agriculture IoT Platform",
    "Farm Equipment Manager","Tractor Fleet Manager","Agri Input Manager","Farmer Training System","Agriculture Budget Manager",
  ],
  legal: [
    "Legal Case Manager Complete","Law Firm ERP Pro","Court Management System","Legal Cloud Manager","Law Firm Cloud ERP",
    "Court Cloud System","Legal AI Manager","Law Firm AI ERP","Court AI System","Client Portal Legal",
    "Document Manager Legal","Contract Manager Pro","Compliance Manager Legal","E-Filing System","Legal Research Platform",
    "Case Tracking System","Hearing Scheduler Pro","Legal Billing System","Trust Accounting System","Time Tracking Legal",
    "Legal CRM System","Legal Analytics Dashboard","Mediation Manager","Arbitration Manager","Legal Notice Manager",
    "Power of Attorney Manager","Will & Estate Manager","Intellectual Property Manager","Patent Manager Pro","Trademark Manager Pro",
    "Copyright Manager Pro","Legal HR System","Legal Payroll","Paralegal Manager","Expert Witness Manager",
    "Evidence Manager Pro","Deposition Manager","Discovery Manager","Trial Manager Pro","Appellate Manager",
    "Legal Knowledge Base","Law Library Manager","Legal Template Manager","Legal Workflow Automation","Legal Risk Manager",
    "Regulatory Compliance Legal","Legal Insurance Manager","Client Intake System","Conflict Check System","Legal Budget Manager",
  ],
  government: [
    "Government ERP Complete","Municipality ERP Pro","Panchayat Management System","Government Cloud ERP","Municipality Cloud ERP",
    "Panchayat Cloud System","Government AI ERP","Municipality AI ERP","Panchayat AI System","E-Governance Platform",
    "Citizen Portal System","Grievance Management System","RTI Management System","Birth Death Registration","Land Record System",
    "Property Tax System","Water Tax System","Trade License System","Building Permission System","Town Planning System",
    "Public Works Manager","Road Management System","Street Light Manager","Water Supply Manager","Sewage Management System",
    "Solid Waste Manager","Park Management System","Cemetery Management System","Government HR System","Government Payroll",
    "Government Accounting","Budget Manager Government","Tender Management Government","Procurement Government","Asset Manager Government",
    "Vehicle Manager Government","Library Government","Museum Manager Government","Tourism Manager Government","Sports Manager Government",
    "Health Department ERP","Education Department ERP","Agriculture Department ERP","Revenue Department ERP","Police Department ERP",
    "Fire Department ERP","Election Management System","Census Management System","Disaster Management System","Government Analytics Dashboard",
  ],
  ngo: [
    "NGO Management Complete","Charity Manager Pro","Foundation ERP System","NGO Cloud Manager","Charity Cloud Pro",
    "Foundation Cloud ERP","NGO AI Manager","Charity AI Pro","Foundation AI ERP","Donor Management System",
    "Fundraising Platform Pro","Grant Manager Pro","Volunteer Manager Pro","Beneficiary Manager","Project Manager NGO",
    "Program Manager NGO","Campaign Manager Pro","Event Manager NGO","Advocacy Platform Pro","NGO CRM System",
    "NGO Analytics Dashboard","Impact Assessment System","M&E System Pro","CSR Manager Pro","Social Enterprise ERP",
    "Microfinance NGO","Self Help Group Manager","Community Development Manager","Child Welfare Manager","Women Empowerment Manager",
    "Education NGO Manager","Health NGO Manager","Environment NGO Manager","Animal Welfare Manager","Disaster Relief Manager",
    "Refugee Management System","Human Rights Manager","Legal Aid Manager","Skill Development NGO","Livelihood Manager",
    "Water Sanitation NGO","Food Bank Manager","Shelter Management System","Rehabilitation NGO Manager","NGO HR System",
    "NGO Payroll","NGO Accounting System","NGO Compliance Manager","NGO Audit Manager","NGO Budget Manager",
  ],
  gym_sports: [
    "Gym Management Complete","Sports Club ERP Pro","Fitness Center Manager","Gym Cloud Manager","Sports Club Cloud",
    "Fitness Cloud Center","Gym AI Manager","Sports AI Club","Fitness AI Center","Member Management System",
    "Trainer Management Pro","Class Scheduler Pro","Equipment Manager Gym","Locker Manager System","Attendance Manager Gym",
    "Billing Manager Gym","PT Session Manager","Nutrition Planner Pro","Workout Builder Pro","Body Measurement Tracker",
    "Gym CRM System","Gym Analytics Dashboard","Multi Branch Gym Manager","Franchise Gym Manager","CrossFit Box Manager",
    "Yoga Studio Manager","Pilates Studio Manager","Dance Studio Manager","Martial Arts Manager","Boxing Gym Manager",
    "Swimming Pool Manager","Tennis Club Manager","Cricket Academy Manager","Football Academy Manager","Basketball Academy Manager",
    "Badminton Club Manager","Table Tennis Club Manager","Golf Club Manager","Squash Club Manager","Athletic Club Manager",
    "Sports League Manager","Tournament Manager Pro","Sports Analytics Pro","Referee Manager System","Ground Booking System",
    "Sports Equipment Manager","Sports Injury Manager","Doping Control Manager","Sports Federation ERP","Sports Budget Manager",
  ],
  salon_spa: [
    "Salon Manager Complete","Spa Management Pro","Beauty Parlor ERP","Salon Cloud Manager","Spa Cloud Pro",
    "Beauty Cloud ERP","Salon AI Manager","Spa AI Pro","Beauty AI ERP","Appointment Booking Salon",
    "Staff Scheduler Salon","Client Manager Salon","Service Menu Manager","Product Inventory Salon","Billing Manager Salon",
    "Commission Manager Salon","Tips Manager Salon","Salon CRM System","Salon Analytics Dashboard","Multi Branch Salon",
    "Franchise Salon Manager","Men Salon Manager","Unisex Salon Manager","Hair Salon Specialist","Nail Salon Manager",
    "Tattoo Studio Manager","Piercing Studio Manager","Waxing Center Manager","Threading Center Manager","Facial Center Manager",
    "Makeup Studio Manager","Bridal Studio Manager","Skin Clinic Manager","Laser Center Manager","Hair Transplant Manager",
    "Ayurvedic Spa Manager","Thai Spa Manager","Aromatherapy Manager","Reflexology Center Manager","Acupuncture Center Manager",
    "Wellness Center Manager","Meditation Center Manager","Sauna & Steam Manager","Hot Spring Manager","Float Center Manager",
    "Cryotherapy Center Manager","Salt Room Manager","Infrared Therapy Manager","Hydrotherapy Manager","Salon Budget Manager",
  ],
  fashion: [
    "Fashion POS Complete","Boutique Manager Pro","Garment ERP System","Fashion Cloud POS","Boutique Cloud Manager",
    "Garment Cloud ERP","Fashion AI POS","Boutique AI Manager","Garment AI ERP","Textile ERP System",
    "Apparel ERP Pro","Fashion Design Studio","Pattern Making System","Cutting Room Manager","Stitching Manager Pro",
    "Quality Check Fashion","Fashion Inventory Manager","Fabric Store Manager","Fashion Wholesale Manager","Fashion Retail Manager",
    "Fashion E-Commerce Platform","Fashion Marketplace","Fashion CRM System","Fashion Analytics Dashboard","Multi Store Fashion",
    "Franchise Fashion Manager","Fashion Show Manager","Fashion Week Manager","Runway Manager Pro","Model Agency Manager",
    "Fashion Photography Manager","Lookbook Manager","Catalog Manager Fashion","Fashion Blog Platform","Fashion Influencer Manager",
    "Shoe Store Manager","Handbag Store Manager","Watch Store Manager","Accessories Store Manager","Sunglasses Store Manager",
    "Ethnic Wear Manager","Western Wear Manager","Kids Wear Manager","Sports Wear Manager","Formal Wear Manager",
    "Casual Wear Manager","Lingerie Store Manager","Swimwear Store Manager","Custom Tailoring Manager","Fashion Budget Manager",
  ],
  ecommerce: [
    "E-Commerce Platform Complete","Multi Vendor Marketplace","B2B E-Commerce Platform","E-Commerce Cloud Platform","Multi Vendor Cloud",
    "B2B Cloud Platform","E-Commerce AI Platform","Multi Vendor AI","B2B AI Platform","Dropshipping Platform",
    "Social Commerce Platform","Live Commerce Platform","Quick Commerce Platform","Subscription Commerce Platform","Headless Commerce Platform",
    "E-Commerce CRM System","E-Commerce Analytics Dashboard","Product Information Manager","Catalog Manager Pro","Order Management System",
    "Inventory E-Commerce","Warehouse E-Commerce","Shipping Manager Pro","Return Management System","Refund Manager Pro",
    "Payment Gateway Integration","Tax Manager E-Commerce","Coupon Manager Pro","Loyalty Program Manager","Affiliate Manager Pro",
    "SEO Manager E-Commerce","Email Marketing E-Commerce","SMS Marketing E-Commerce","Push Notification E-Commerce","Chatbot E-Commerce",
    "Customer Review System","Wishlist Manager","Cart Abandonment System","Price Comparison Engine","Deal Aggregator Platform",
    "Flash Sale Manager","Group Buy Platform","Auction Platform Pro","Classified Ads Platform","Rental Marketplace Platform",
    "Service Marketplace","Freelance Marketplace","Digital Products Store","NFT Marketplace","E-Commerce Budget Manager",
  ],
  mlm: [
    "MLM Software Complete","Network Marketing Platform","Direct Selling ERP","MLM Cloud Software","Network Marketing Cloud",
    "Direct Selling Cloud","MLM AI Software","Network Marketing AI","Direct Selling AI","Binary Plan MLM",
    "Matrix Plan MLM","Unilevel Plan MLM","Board Plan MLM","Stair Step Plan MLM","Hybrid Plan MLM",
    "Generation Plan MLM","MLM E-Commerce Platform","MLM Wallet System","MLM Payout Manager","MLM Commission Engine",
    "MLM Genealogy Tree","MLM Lead Manager","MLM Training Platform","MLM Replicated Website","MLM Mobile App",
    "MLM Analytics Dashboard","MLM Compliance Manager","MLM Tax Manager","MLM Event Manager","MLM Reward System",
    "MLM Rank Manager","MLM Incentive Trip Manager","MLM Auto Pool System","MLM Party Plan","MLM Crowdfunding",
    "MLM Cryptocurrency","MLM Health Products","MLM Beauty Products","MLM Travel Products","MLM Education Products",
    "MLM Financial Products","MLM Insurance Products","MLM Real Estate","MLM Automotive","MLM Food Products",
    "MLM Fashion Products","MLM Technology Products","MLM Energy Products","MLM Agriculture Products","MLM Budget Manager",
  ],
  billing: [
    "Billing Software Complete","Invoice Manager Pro","GST Billing System","Billing Cloud Software","Invoice Cloud Manager",
    "GST Cloud System","Billing AI Software","Invoice AI Manager","GST AI System","Recurring Billing System",
    "Subscription Billing Pro","Usage Based Billing","Metered Billing System","Prepaid Billing System","Postpaid Billing System",
    "Utility Billing System","Telecom Billing System","ISP Billing System","Cable TV Billing","Water Billing System",
    "Electricity Billing System","Gas Billing System","Parking Billing System","Toll Billing System","Laundry Billing System",
    "Dry Cleaning Billing","Printing Press Billing","Photography Billing","Catering Billing System","Event Billing System",
    "Tuition Billing System","Coaching Billing System","Gym Billing System","Salon Billing System","Clinic Billing System",
    "Dental Billing System","Veterinary Billing","Legal Billing System","Consulting Billing System","Freelance Billing System",
    "Project Billing System","Time Based Billing","Milestone Billing System","Progress Billing System","Advance Billing System",
    "Pro Rata Billing System","Split Billing System","Group Billing System","Consolidated Billing","Billing Budget Manager",
  ],
  transport: [
    "Transport ERP Complete","Bus Management System","Taxi Management System","Transport Cloud ERP","Bus Cloud Manager",
    "Taxi Cloud Manager","Transport AI ERP","Bus AI Manager","Taxi AI Manager","Auto Rickshaw Manager",
    "Truck Management System","Van Management System","Car Rental Manager","Bike Rental Manager","Scooter Rental Manager",
    "School Transport Manager","Corporate Transport Manager","Employee Transport Manager","Airport Transfer Manager","Railway Manager System",
    "Metro Management System","Tram Management System","Ferry Management System","Cable Car Manager","Helicopter Service Manager",
    "Ambulance Fleet Manager","Police Vehicle Manager","Fire Truck Manager","Garbage Truck Manager","Construction Vehicle Manager",
    "Mining Vehicle Manager","Agriculture Vehicle Manager","Delivery Vehicle Manager","Food Delivery Fleet","Courier Fleet Manager",
    "Moving & Relocation Manager","Towing Service Manager","Driving School Manager","Vehicle Inspection System","RTO Management System",
    "Toll Management System","Parking Management System","Fuel Station Manager","EV Charging Manager","Vehicle Insurance Manager",
    "Vehicle Loan Manager","Vehicle Auction Manager","Vehicle Scrap Manager","Transport Analytics Dashboard","Transport Budget Manager",
  ],
  hrms: [
    "HRMS Complete Suite","HR Manager Pro","People Management System","HRMS Cloud Suite","HR Cloud Manager",
    "People Cloud System","HRMS AI Suite","HR AI Manager","People AI System","Recruitment Manager Pro",
    "Applicant Tracking System","Onboarding Manager Pro","Employee Self Service","Leave Management System","Attendance Management System",
    "Shift Management System","Overtime Manager Pro","Travel & Expense Manager","Performance Management System","Appraisal Manager Pro",
    "Goal Setting Manager","KPI Manager Pro","360 Feedback System","Training Manager Pro","Learning & Development Manager",
    "Succession Planning System","Career Development Manager","Employee Engagement System","Survey Manager HR","Grievance Manager HR",
    "Disciplinary Manager","Exit Management System","Offboarding Manager","Alumni Manager Pro","HR Analytics Dashboard",
    "HR Compliance Manager","HR Policy Manager","HR Document Manager","Organization Chart Manager","Manpower Planning System",
    "Workforce Analytics Pro","Employee Wellness Manager","Benefits Manager Pro","Compensation Manager","Job Evaluation System",
    "Competency Manager Pro","Talent Pool Manager","Campus Recruitment Manager","Vendor Management HR","HR Budget Manager",
  ],
  payroll: [
    "Payroll Software Complete","Salary Manager Pro","Wage Management System","Payroll Cloud Software","Salary Cloud Manager",
    "Wage Cloud System","Payroll AI Software","Salary AI Manager","Wage AI System","Multi Country Payroll",
    "Multi Currency Payroll","Statutory Compliance Payroll","PF Manager Pro","ESI Manager Pro","Professional Tax Manager",
    "TDS Manager Payroll","Income Tax Manager","Bonus Calculator Pro","Gratuity Calculator Pro","Leave Encashment Manager",
    "Overtime Calculator Pro","Arrears Calculator Pro","Payslip Generator Pro","Bank Transfer Payroll","Cash Disbursement Payroll",
    "Payroll Analytics Dashboard","Payroll Audit Manager","Payroll Reconciliation","Cost to Company Calculator","Salary Structure Manager",
    "Pay Grade Manager","Pay Band Manager","Allowance Manager Pro","Deduction Manager Pro","Reimbursement Manager",
    "Advance Salary Manager","Loan Against Salary","Salary Revision Manager","Increment Manager Pro","Payroll Calendar Manager",
    "Payroll Integration Suite","Payroll Outsourcing Manager","Contractor Payroll","Freelance Payroll","Gig Worker Payroll",
    "Part Time Payroll","Seasonal Worker Payroll","Daily Wage Payroll","Commission Payroll","Payroll Budget Manager",
  ],
  warehouse: [
    "Warehouse ERP Complete","Inventory Warehouse Pro","WMS Pro System","Warehouse Cloud ERP","Inventory Cloud Warehouse",
    "WMS Cloud System","Warehouse AI ERP","Inventory AI Warehouse","WMS AI System","Multi Warehouse Manager",
    "Cold Storage WMS","Bonded Warehouse Manager","Free Trade Zone WMS","E-Commerce Warehouse","Fulfillment Center Manager",
    "Cross Docking Manager","Pick Pack Ship System","Putaway Manager Pro","Cycle Count Manager","Physical Inventory Manager",
    "Lot Tracking System","Serial Number Tracking","Expiry Management System","FIFO LIFO Manager","ABC Analysis Manager",
    "Bin Location Manager","Zone Management System","Wave Planning Manager","Labor Management Warehouse","Dock Management System",
    "Yard Management WMS","Receiving Manager Pro","Shipping Manager WMS","Return Processing WMS","Damage Management System",
    "Warehouse Analytics Dashboard","Warehouse KPI Manager","Space Utilization Manager","Warehouse Safety Manager","Forklift Management System",
    "Conveyor Management System","AGV Management System","AS/RS Manager Pro","Voice Picking System","RF Scanning System",
    "Barcode System Warehouse","RFID System Warehouse","Warehouse Integration Suite","Warehouse Billing System","Warehouse Budget Manager",
  ],
  pharmacy: [
    "Pharmacy ERP Complete","Drug Store Manager Pro","Medical Store POS","Pharmacy Cloud ERP","Drug Store Cloud",
    "Medical Store Cloud","Pharmacy AI ERP","Drug Store AI","Medical Store AI","Chain Pharmacy Manager",
    "Hospital Pharmacy Manager","Clinical Pharmacy Manager","Compounding Pharmacy Manager","Online Pharmacy Platform","Pharmacy E-Commerce",
    "Prescription Manager Pro","Drug Inventory Manager","Expiry Tracking Pharmacy","Batch Tracking Pharmacy","Narcotic Drug Manager",
    "Controlled Substance Manager","Drug Interaction Checker","Formulary Manager Pro","Drug Information System","Pharmacy Billing Pro",
    "Insurance Billing Pharmacy","Pharmacy POS System","Pharmacy Analytics Dashboard","Pharmacy CRM System","Patient Counseling System",
    "Medication Therapy Manager","Adverse Drug Reaction Manager","Pharmacovigilance System","Drug Recall Manager","Pharmacy Compliance Manager",
    "Pharmacy License Manager","Drug Schedule Manager","Pharmacy Audit Manager","Pharmacy HR System","Pharmacy Payroll",
    "Pharmacy Accounting","Pharmacy Procurement","Vendor Manager Pharmacy","Wholesale Pharmacy Manager","Distribution Pharmacy Manager",
    "Pharmacy Lab Manager","Pharmacy Research Manager","Pharmacy Training System","Telepharmacy Platform","Pharmacy Budget Manager",
  ],
  clinic: [
    "Clinic Manager Complete","Doctor Practice Manager","Polyclinic ERP Pro","Clinic Cloud Manager","Doctor Cloud Practice",
    "Polyclinic Cloud ERP","Clinic AI Manager","Doctor AI Practice","Polyclinic AI ERP","Appointment Booking Clinic",
    "Patient Registration System","Electronic Medical Records","Prescription Manager Clinic","Lab Order Manager","Imaging Order Manager",
    "Referral Manager Clinic","Billing Manager Clinic","Insurance Claims Clinic","Patient Portal Clinic","Telemedicine Clinic",
    "Clinic Analytics Dashboard","Multi Specialty Clinic ERP","Single Specialty Clinic ERP","Dental Clinic Manager","Eye Clinic Manager",
    "ENT Clinic Manager","Skin Clinic Manager","Orthopedic Clinic Manager","Cardiology Clinic Manager","Neurology Clinic Manager",
    "Pediatric Clinic Manager","Gynecology Clinic Manager","Urology Clinic Manager","Physiotherapy Clinic Manager","Ayurvedic Clinic Manager",
    "Homeopathy Clinic Manager","Acupuncture Clinic Manager","Chiropractic Clinic Manager","Dietitian Clinic Manager","Psychology Clinic Manager",
    "Speech Therapy Clinic","Occupational Therapy Clinic","Fertility Clinic Manager","IVF Center Manager","Dialysis Center Manager",
    "Chemotherapy Center Manager","Wound Care Clinic Manager","Pain Management Clinic","Addiction Treatment Center","Clinic Budget Manager",
  ],
  telecom: [
    "Telecom Billing Complete","ISP Management System","Cable TV Management","Telecom Cloud Billing","ISP Cloud Manager",
    "Cable TV Cloud Manager","Telecom AI Billing","ISP AI Manager","Cable TV AI Manager","Mobile Operator ERP",
    "Fiber Optic Manager","Broadband Manager Pro","DTH Management System","IPTV Management System","VoIP Management System",
    "UCaaS Platform Pro","CPaaS Platform Pro","Telecom CRM System","Telecom Analytics Dashboard","Network Management System",
    "Tower Management System","Cell Site Manager","Spectrum Manager Pro","Roaming Manager System","Interconnect Billing System",
    "Revenue Assurance System","Fraud Management Telecom","Number Portability Manager","SIM Management System","Device Management System",
    "Content Delivery Manager","Value Added Service Manager","Telecom Provisioning System","Service Activation System","Trouble Ticket System",
    "Field Service Telecom","Workforce Manager Telecom","Inventory Manager Telecom","Asset Manager Telecom","Vendor Manager Telecom",
    "Telecom Compliance Manager","Telecom License Manager","Telecom Project Manager","Telecom HR System","Telecom Payroll",
    "Telecom Accounting","Telecom Procurement","OSS/BSS Platform","Telecom Reporting Suite","Telecom Budget Manager",
  ],
  cybersecurity: [
    "Cybersecurity Suite Complete","SIEM Platform Pro","SOC Manager System","Cybersecurity Cloud Suite","SIEM Cloud Platform",
    "SOC Cloud Manager","Cybersecurity AI Suite","SIEM AI Platform","SOC AI Manager","Vulnerability Scanner Pro",
    "Penetration Testing Manager","Threat Intelligence Platform","Incident Response Manager","Digital Forensics Platform","Malware Analysis System",
    "Endpoint Protection Manager","Network Security Manager","Firewall Manager Pro","IDS/IPS Manager Pro","WAF Manager System",
    "DDoS Protection Manager","Email Security Manager","Web Security Manager","Cloud Security Manager","Mobile Security Manager",
    "IoT Security Manager","API Security Manager","Database Security Manager","Application Security Manager","Container Security Manager",
    "DevSecOps Platform","Security Compliance Manager","GRC Platform Pro","Risk Assessment Manager","Security Audit Manager",
    "Identity Access Manager","PAM System Pro","SSO Manager Pro","MFA Manager Pro","Certificate Manager Pro",
    "Encryption Manager Pro","Data Loss Prevention","Backup Security Manager","Disaster Recovery Manager","Business Continuity Manager",
    "Security Awareness Training","Phishing Simulation Manager","Dark Web Monitor","Brand Protection Manager","Cybersecurity Budget Manager",
  ],
  data_analytics: [
    "Data Analytics Platform Complete","Business Intelligence Suite","Reporting Engine Pro","Analytics Cloud Platform","BI Cloud Suite",
    "Reporting Cloud Engine","Analytics AI Platform","BI AI Suite","Reporting AI Engine","Data Warehouse Manager",
    "ETL Pipeline Manager","Data Lake Platform","Data Catalog Manager","Data Quality Manager","Data Governance Platform",
    "Master Data Manager","Metadata Manager Pro","Data Lineage Manager","Real Time Analytics Platform","Streaming Analytics Pro",
    "Predictive Analytics Platform","Prescriptive Analytics Pro","Descriptive Analytics Pro","Diagnostic Analytics Pro","Embedded Analytics Platform",
    "Self Service Analytics","Mobile Analytics Pro","Social Media Analytics","Web Analytics Platform","Marketing Analytics Pro",
    "Sales Analytics Pro","Financial Analytics Pro","HR Analytics Pro","Supply Chain Analytics","Customer Analytics Pro",
    "Product Analytics Pro","Operations Analytics","Healthcare Analytics Pro","Education Analytics Pro","Government Analytics Pro",
    "Retail Analytics Pro","Manufacturing Analytics","Logistics Analytics Pro","Energy Analytics Pro","Telecom Analytics Pro",
    "Dashboard Builder Pro","Visualization Engine","Natural Language Query","Automated Insights Engine","Analytics Budget Manager",
  ],
  investment: [
    "Investment Manager Complete","Portfolio Tracker Pro","Wealth Management Platform","Investment Cloud Manager","Portfolio Cloud Tracker",
    "Wealth Cloud Platform","Investment AI Manager","Portfolio AI Tracker","Wealth AI Platform","Mutual Fund Tracker",
    "Stock Portfolio Manager","Bond Portfolio Manager","ETF Portfolio Manager","Commodity Tracker Pro","Derivatives Manager Pro",
    "Options Trading Manager","Futures Trading Manager","Forex Portfolio Manager","Crypto Portfolio Manager","Real Estate Investment Tracker",
    "Private Equity Manager","Venture Capital Manager","Angel Investment Manager","Hedge Fund Manager","Fund of Funds Manager",
    "SIP Manager Pro","Systematic Transfer Manager","Goal Based Investment","Tax Saving Investment Manager","Retirement Planning Manager",
    "Education Fund Manager","Wedding Fund Manager","Emergency Fund Manager","Insurance Investment Manager","NPS Manager Pro",
    "PPF Manager Pro","Fixed Deposit Manager","Recurring Deposit Manager","Gold Investment Manager","Silver Investment Manager",
    "Art Investment Manager","Wine Investment Manager","Collectibles Manager","P2P Lending Platform","Crowdfunding Investment Platform",
    "Robo Advisor Platform","Investment Advisory Manager","Research Analyst Platform","Back Testing Engine","Investment Budget Manager",
  ],
  crypto_forex: [
    "Crypto Exchange Complete","Forex Trading Platform","DeFi Platform Pro","Crypto Cloud Exchange","Forex Cloud Platform",
    "DeFi Cloud Pro","Crypto AI Exchange","Forex AI Platform","DeFi AI Pro","Bitcoin Trading Platform",
    "Ethereum Trading Platform","Altcoin Exchange Pro","Token Launch Platform","ICO Manager Pro","IEO Manager Pro",
    "IDO Launchpad Pro","NFT Marketplace Pro","Crypto Wallet System","Cold Wallet Manager","Hot Wallet Manager",
    "Crypto Payment Gateway","Crypto Billing System","Crypto Accounting System","Crypto Tax Manager","Crypto Compliance Manager",
    "Crypto Analytics Platform","Crypto Portfolio Tracker","Crypto Copy Trading","Crypto Bot Manager","Crypto Signals Platform",
    "Crypto News Aggregator","Crypto Social Platform","Crypto Learning Platform","Crypto Mining Manager","Crypto Staking Platform",
    "Crypto Lending Platform","Crypto Borrowing Platform","Crypto Yield Farming","Liquidity Pool Manager","DEX Platform Pro",
    "CEX Platform Pro","OTC Trading Platform","P2P Crypto Platform","Crypto Escrow System","Crypto KYC System",
    "Crypto AML System","Crypto Audit Trail","Smart Contract Manager","Blockchain Explorer Pro","Crypto Budget Manager",
  ],
  insurance: [
    "Insurance ERP Complete","Life Insurance Manager","Health Insurance Manager","Insurance Cloud ERP","Life Cloud Manager",
    "Health Cloud Manager","Insurance AI ERP","Life AI Manager","Health AI Manager","Motor Insurance Manager",
    "Property Insurance Manager","Travel Insurance Manager","Marine Insurance Manager","Crop Insurance Manager","Livestock Insurance Manager",
    "Business Insurance Manager","Liability Insurance Manager","Workers Comp Manager","Professional Indemnity Manager","Cyber Insurance Manager",
    "Policy Administration System","Underwriting Manager Pro","Claims Manager Pro","Reinsurance Manager Pro","Actuarial Analysis System",
    "Insurance CRM System","Agent Manager Pro","Broker Manager Pro","Commission Manager Insurance","Lead Manager Insurance",
    "Proposal Manager Insurance","Premium Calculator Pro","Quote Engine Pro","Renewal Manager Pro","Lapse Management System",
    "Insurance Analytics Dashboard","Insurance Compliance Manager","Insurance Fraud Detection","Insurance Document Manager","Insurance Workflow Manager",
    "Micro Insurance Platform","Index Insurance Platform","Parametric Insurance Platform","Embedded Insurance Platform","InsurTech Platform Pro",
    "Insurance Aggregator Platform","Insurance Comparison Tool","Insurance Training Platform","Insurance Exam Manager","Insurance Budget Manager",
  ],
  dairy: [
    "Dairy ERP Complete","Milk Collection System","Dairy Processing Manager","Dairy Cloud ERP","Milk Cloud Collection",
    "Processing Cloud Manager","Dairy AI ERP","Milk AI Collection","Processing AI Manager","Milk Route Manager",
    "Milk Quality Tester","Fat Testing System","SNF Testing System","Milk Procurement Manager","Milk Price Calculator",
    "Dairy Cooperative Manager","Dairy Farmer Portal","Cattle Management System","Feed Management Dairy","Breeding Manager Dairy",
    "Veterinary Manager Dairy","Milk Chilling Center Manager","Pasteurization Manager","Homogenization Manager","Cream Separator Manager",
    "Butter Making Manager","Cheese Making Manager","Yogurt Making Manager","Ice Cream Making Manager","Paneer Making Manager",
    "Ghee Making Manager","Milk Powder Manager","Condensed Milk Manager","Flavored Milk Manager","Dairy Packaging Manager",
    "Dairy Cold Chain Manager","Dairy Distribution Manager","Dairy Retail Manager","Dairy E-Commerce","Dairy Analytics Dashboard",
    "Dairy Quality Control","Dairy Compliance Manager","Dairy Lab Manager","Dairy HR System","Dairy Payroll",
    "Dairy Accounting System","Dairy Procurement","Dairy Asset Manager","Dairy Fleet Manager","Dairy Budget Manager",
  ],
  mining: [
    "Mining ERP Complete","Mine Planning System","Ore Processing Manager","Mining Cloud ERP","Mine Cloud Planning",
    "Ore Cloud Processing","Mining AI ERP","Mine AI Planning","Ore AI Processing","Geological Survey Manager",
    "Mineral Exploration Manager","Drill Hole Manager","Sample Analysis System","Reserve Estimation System","Mine Design System",
    "Blast Design Manager","Excavation Manager Pro","Loading Hauling Manager","Crusher Manager Pro","Grinding Mill Manager",
    "Flotation Manager Pro","Leaching Manager Pro","Smelting Manager Pro","Refining Manager Pro","Tailings Manager Pro",
    "Mine Safety Manager","Mine Ventilation Manager","Mine Dewatering Manager","Mine Rehabilitation Manager","Environmental Mining Manager",
    "Mining Compliance Manager","Mining License Manager","Mining Royalty Manager","Mining Analytics Dashboard","Mining CRM System",
    "Mining HR System","Mining Payroll","Mining Accounting","Mining Procurement","Mining Asset Manager",
    "Mining Fleet Manager","Mining Equipment Manager","Mining Inventory Manager","Mining Surveying System","Mining Communication System",
    "Mining Emergency Manager","Mining Training System","Mining Quality Control","Mining Logistics Manager","Mining Budget Manager",
  ],
  energy: [
    "Energy ERP Complete","Solar Energy Manager","Wind Energy Manager","Energy Cloud ERP","Solar Cloud Manager",
    "Wind Cloud Manager","Energy AI ERP","Solar AI Manager","Wind AI Manager","Hydropower Manager Pro",
    "Biomass Energy Manager","Geothermal Energy Manager","Nuclear Energy Manager","Thermal Power Manager","Gas Power Manager",
    "Coal Power Manager","Diesel Power Manager","Hybrid Power Manager","Microgrid Manager Pro","Smart Grid Manager",
    "Energy Storage Manager","Battery Management System","EV Charging Manager","Power Distribution Manager","Transmission Manager Pro",
    "Substation Manager Pro","Transformer Manager Pro","Switchgear Manager Pro","Cable Management System","Power Quality Manager",
    "Load Forecasting System","Energy Trading Platform","Renewable Energy Certificate Manager","Carbon Credit Manager","Energy Audit Manager",
    "Energy Efficiency Manager","Building Energy Manager","Industrial Energy Manager","Agricultural Energy Manager","Residential Energy Manager",
    "Energy Analytics Dashboard","Energy Compliance Manager","Energy Safety Manager","Energy HR System","Energy Payroll",
    "Energy Accounting","Energy Procurement","Energy Asset Manager","Energy Project Manager","Energy Budget Manager",
  ],
  iot_factory: [
    "IoT Factory Platform Complete","Smart Factory Manager","Industry 4.0 Platform","IoT Cloud Factory","Smart Cloud Factory",
    "Industry Cloud 4.0","IoT AI Factory","Smart AI Factory","Industry AI 4.0","Sensor Management Platform",
    "Device Management IoT","Gateway Manager Pro","Edge Computing Manager","Fog Computing Manager","IoT Data Platform",
    "IoT Analytics Dashboard","IoT Security Manager","Digital Twin Manager","Predictive Maintenance IoT","Condition Monitoring System",
    "Vibration Analysis System","Temperature Monitoring System","Pressure Monitoring System","Flow Monitoring System","Level Monitoring System",
    "Energy Monitoring IoT","Water Monitoring IoT","Air Quality Monitor IoT","Noise Monitoring IoT","Light Monitoring IoT",
    "Asset Tracking IoT","Fleet Tracking IoT","Personnel Tracking IoT","Container Tracking IoT","Pallet Tracking IoT",
    "Smart Warehouse IoT","Smart Logistics IoT","Smart Agriculture IoT","Smart Building IoT","Smart City Platform",
    "Smart Home Platform","Smart Health IoT","Smart Retail IoT","Smart Parking IoT","Smart Lighting IoT",
    "IoT Protocol Manager","IoT Firmware Manager","IoT OTA Update Manager","IoT Dashboard Builder","IoT Budget Manager",
  ],
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    let totalInserted = 0;
    const errors: string[] = [];

    for (const [category, names] of Object.entries(CATEGORIES)) {
      const rows = names.map((name, i) => {
        const slug = `${category}-${name}`.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "");
        const code = `PRD-${category.substring(0, 3).toUpperCase()}${String(i + 1).padStart(3, "0")}`;
        const isUpcoming = category === "upcoming";

        return {
          name,
          slug,
          product_code: code,
          status: isUpcoming ? "draft" : "active",
          price: 5,
          marketplace_visible: true,
          business_type: category,
          short_description: `Professional ${name} — Enterprise Grade Solution with Full Support`,
          features: JSON.stringify(["Dashboard", "Reports", "Multi User", "24/7 Support"]),
          tech_stack_json: JSON.stringify(["React", "Node.js", "PostgreSQL", "AWS", "Docker"]),
          demo_enabled: !isUpcoming,
          featured: i < 3,
          trending: i < 5,
          deploy_status: isUpcoming ? "pending" : "idle",
        };
      });

      // Insert in batch of 50
      const { error } = await supabase.from("products").insert(rows);
      if (error) {
        errors.push(`${category}: ${error.message}`);
      } else {
        totalInserted += rows.length;
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        totalInserted,
        totalCategories: Object.keys(CATEGORIES).length,
        errors: errors.length > 0 ? errors : undefined,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err: any) {
    return new Response(
      JSON.stringify({ success: false, error: err.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
